services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      HTTP_PORT: 3000
      POSTGRESQL_READS_HOST: "quadrant-postgres"
      POSTGRESQL_READS_DBNAME: "domain_accommodations"
      POSTGRESQL_READS_USERNAME: "postgres"
      POSTGRESQL_READS_PASSWORD: "postgres"
      POSTGRESQL_READS_SCHEMA: "main_reads"
    volumes:
      - ./:/app
    command: air -c .air.toml

networks:
  default:
    name: quadrant-network
    external: true