services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      HTTP_PORT: 3000
    volumes:
      - ./:/app
    command: air -c .air.toml

networks:
  default:
    name: quadrant-network
    external: true